@api = http://localhost:3000/productos
@api2 = http://localhost:3000/datesbyfecha

@api3 = http://localhost:3000/users

@f = "2022/11/02"
##




###
POST {{api}}
Content-Type: application/json

{
    "id_tienda": 1,
    "nombre": "pera",
    "descripcion": "fruta verde",
    "cantidad": 12,
    "precio_costo": 10,
    "precio_venta": 15
}
###
GET {{api3}}/70

###
GET {{api}}/1

###
GET {{api2}}/juan
###
DELETE {{api3}}/69


###
POST {{api}}
Content-Type: application/json

{
    "nombre": "juan",
    "descripcion": "dolor de patas",
    "fecha": "25/10/2022"
}

###
PUT {{api3}}/74
CONTENT-TYPE: application/json

{
    "nombre": "felipe",
    "email": "papa@gmail.com",
    "rol": "cliente",
    "direccion": "colima",
    "tel": 102150
}