@api = http://localhost:3000/productos
@api2 = http://localhost:3000/datesbyfecha

@api3 = http://localhost:3000/dates/user

@f = "2022/11/02"
##




###
POST {{api}}
Content-Type: application/json

{
    "id_tienda": 1,
    "nombre": "pera",
    "descripcion": "fruta verde",
    "cantidad": 12,
    "precio_costo": 10,
    "precio_venta": 15
}
###
GET {{api}}

###
GET {{api}}/1

###
GET {{api2}}/juan
###
DELETE {{api}}/11


###
POST {{api}}
Content-Type: application/json

{
    "nombre": "juan",
    "descripcion": "dolor de patas",
    "fecha": "25/10/2022"
}

###
PUT {{api}}/1
CONTENT-TYPE: application/json

{
    "id_tienda": 1,
    "nombre": "mango",
    "descripcion": "fruta amarilla",
    "cantidad": 12,
    "precio_costo": 10,
    "precio_venta": 15
}